spring:
  datasource:
    url: jdbc:mysql://x.x.x:3306/airdrop?createDatabaseIfNotExist=true&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai
    username: root
    password: 212
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3  # 最小空闲连接数量
      maximum-pool-size: 5  # 连接池最大连接数，默认是10
      max-lifetime: 1800000  # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-test-query: SELECT 1
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 5MB
      max-request-size: 25MB

server:
  port: 8083
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

web3j:
  client-address: http://localhost:8545
  addr: "0x23E53c3882B64B0907C831cFe7198c0a9a125e33"
  pwd: 123456
  private-key: 784ea4998e2091b656301e0a6a6182dc4d44aec8d7374310dc873dfe122c2f93
  gas-price: 20_000_000L
  gas-limit: 1_30000_0L

files:
  uploadFilePath: /File/
  virtualUploadPath: /file/
